In [14]:
import pandas as pd



patients_df = pd.read_csv(r"C:\Users\jsuya\Desktop\Data_1\synthea_data\patients.csv")
encounters_df = pd.read_csv(r"C:\Users\jsuya\Desktop\Data_1\synthea_data\encounters.csv")
conditions_df  = pd.read_csv(r"C:\Users\jsuya\Desktop\Data_1\synthea_data\conditions.csv")
observations_df = pd.read_csv(r"C:\Users\jsuya\Desktop\Data_1\synthea_data\observations.csv")

In [16]:
# Preview patients table
print("Patients Table ")
patients_df.head(3)

Patients Table

,Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,MIDDLE,LAST,...,CITY,STATE,COUNTY,FIPS,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,INCOME
0,69af9fdb-6026-cf15-8110-60645be1a286,1951-01-15,NaN,999-83-1923,S99995838,X13314221X,Mrs.,Sasha806,Ashlie138,Stamm704,...,Uxbridge,Massachusetts,Worcester County,NaN,0,42.048896,-71.644746,781858.42,182267.18,53813
1,e2b7d298-e3e5-8e5a-804c-a8342fdeb164,1957-10-27,NaN,999-52-6475,S99916774,X60183820X,Mrs.,Shawnta32,Janeth814,Hintz995,...,Danvers,Massachusetts,Essex County,25009.0,1937,42.550276,-70.987312,617728.28,860065.14,109027
2,ca4f2fef-0fea-5cdb-314c-9d6689cfabb0,2005-12-04,NaN,999-56-6377,S99960468,X16189809X,Ms.,Haley279,Deandra603,Ondricka197,...,Fitchburg,Massachusetts,Worcester County,25027.0,1420,42.585057,-71.835094,11148.62,726893.50,125882

In [17]:
# Preview encounters table
print("Encounters Table Preview:")
encounters_df.head(3)

Encounters Table Preview:

,Id,START,STOP,PATIENT,ORGANIZATION,PROVIDER,PAYER,ENCOUNTERCLASS,CODE,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONCODE,REASONDESCRIPTION
0,e2b7d298-e3e5-8e5a-c8d2-10b464f4ec42,1973-12-09T14:41:59Z,1973-12-09T14:56:59Z,e2b7d298-e3e5-8e5a-804c-a8342fdeb164,0be0e035-8dad-387e-bbdd-a5a469c4311f,bf882610-fba0-314f-b504-510f1ec422f7,e03e23c9-4df1-3eb6-a62d-f70f02301496,wellness,410620009,Well child visit (procedure),136.8,778.78,0.00,NaN,NaN
1,69af9fdb-6026-cf15-5a00-372c84c0e4fa,1969-03-10T00:14:37Z,1969-03-10T00:57:02Z,69af9fdb-6026-cf15-8110-60645be1a286,d613e441-68e8-3502-8adb-3f770a1276bf,2fb3850d-e660-3483-86b3-aebc3e39ac87,e03e23c9-4df1-3eb6-a62d-f70f02301496,wellness,162673000,General examination of patient (procedure),136.8,962.30,0.00,NaN,NaN
2,69af9fdb-6026-cf15-1cb6-f99e68e93176,1993-01-25T00:14:37Z,1993-01-25T00:58:37Z,69af9fdb-6026-cf15-8110-60645be1a286,d613e441-68e8-3502-8adb-3f770a1276bf,2fb3850d-e660-3483-86b3-aebc3e39ac87,df166300-5a78-3502-a46a-832842197811,wellness,162673000,General examination of patient (procedure),136.8,1133.12,983.12,NaN,NaN

In [18]:
# Preview conditions table
print("Conditions Table Preview:")
conditions_df.head(3)

Conditions Table Preview:

,START,STOP,PATIENT,ENCOUNTER,SYSTEM,CODE,DESCRIPTION
0,1969-03-10,NaN,69af9fdb-6026-cf15-8110-60645be1a286,69af9fdb-6026-cf15-5a00-372c84c0e4fa,http://snomed.info/sct,224299000,Received higher education (finding)
1,1993-01-25,NaN,69af9fdb-6026-cf15-8110-60645be1a286,69af9fdb-6026-cf15-1cb6-f99e68e93176,http://snomed.info/sct,162864005,Body mass index 30+ - obesity (finding)
2,2001-01-15,NaN,69af9fdb-6026-cf15-8110-60645be1a286,69af9fdb-6026-cf15-329f-6dbe9af1a8b4,http://snomed.info/sct,714628002,Prediabetes (finding)

In [28]:
import hashlib

def hash_value(val):
    """Takes any value and returns a short SHA-256 hash string."""
    if pd.isnull(val):
        return None
    return hashlib.sha256(str(val).encode()).hexdigest()[:16]  # first 16 chars only

pii_columns = ["FIRST","MIDDLE" "LAST", "SSN", "ADDRESS"]


patients_masked = patients_df.copy()

patients_masked["HASHED_ID"] = patients_masked["Id"].apply(hash_value)

# Drop only the PII columns that actually exist
cols_to_drop = [c for c in pii_columns if c in patients_masked.columns]
patients_masked.drop(columns=cols_to_drop, inplace=True)

print("PII columns removed:", cols_to_drop)
patients_masked.head(3)

PII columns removed: ['FIRST', 'SSN', 'ADDRESS']

,Id,BIRTHDATE,DEATHDATE,DRIVERS,PASSPORT,PREFIX,MIDDLE,LAST,SUFFIX,MAIDEN,...,STATE,COUNTY,FIPS,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,INCOME,HASHED_ID
0,69af9fdb-6026-cf15-8110-60645be1a286,1951-01-15,NaN,S99995838,X13314221X,Mrs.,Ashlie138,Stamm704,NaN,Runolfsson901,...,Massachusetts,Worcester County,NaN,0,42.048896,-71.644746,781858.42,182267.18,53813,780f438829b05f6c
1,e2b7d298-e3e5-8e5a-804c-a8342fdeb164,1957-10-27,NaN,S99916774,X60183820X,Mrs.,Janeth814,Hintz995,NaN,Cummerata161,...,Massachusetts,Essex County,25009.0,1937,42.550276,-70.987312,617728.28,860065.14,109027,622014c1990471b2
2,ca4f2fef-0fea-5cdb-314c-9d6689cfabb0,2005-12-04,NaN,S99960468,X16189809X,Ms.,Deandra603,Ondricka197,NaN,NaN,...,Massachusetts,Worcester County,25027.0,1420,42.585057,-71.835094,11148.62,726893.50,125882,8cb3f03ca7ff8bf6

In [21]:

encounters_df["HASHED_ID"]   = encounters_df["PATIENT"].apply(hash_value)
conditions_df["HASHED_ID"]   = conditions_df["PATIENT"].apply(hash_value)
observations_df["HASHED_ID"] = observations_df["PATIENT"].apply(hash_value)

print("HASHED_ID added to Encounters, Conditions, Observations tables!")
print("Sample hashed IDs from encounters:")
encounters_df[["PATIENT","HASHED_ID"]].drop_duplicates().head(4)

HASHED_ID added to Encounters, Conditions, Observations tables!
Sample hashed IDs from encounters:

                                 PATIENT         HASHED_ID
0   e2b7d298-e3e5-8e5a-804c-a8342fdeb164  622014c1990471b2
1   69af9fdb-6026-cf15-8110-60645be1a286  780f438829b05f6c
15  ca4f2fef-0fea-5cdb-314c-9d6689cfabb0  8cb3f03ca7ff8bf6
66  36a8268b-0e08-f9d6-6999-eca371aab83c  f55ae149d39d40c6

In [ ]:
total_cost = (
    encounters_df
    .groupby("HASHED_ID")["TOTAL_CLAIM_COST"]
    .sum()
    .reset_index()
    .rename(columns={"TOTAL_CLAIM_COST": "TOTAL_ENCOUNTER_COST"})
)

print("Total Encounter Cost per patient sample:")
total_cost.head()

Total Encounter Cost per patient (sample):

          HASHED_ID  TOTAL_ENCOUNTER_COST
0  000cb1a8e6d680ed             355226.99
1  006ce169b9e12fc2             291242.86
2  016d6b205fcad1b8              71366.46
3  0294ccaffa0df40b              32560.21
4  038dc7dea4d1a27d              59261.96

In [ ]:
conditions_df["START"] = pd.to_datetime(conditions_df["START"], errors="coerce")

latest_condition = (
    conditions_df
    .sort_values("START", ascending=False)
    .drop_duplicates(subset="HASHED_ID", keep="first")
    [["HASHED_ID", "DESCRIPTION", "START"]]
    .rename(columns={
        "DESCRIPTION": "LATEST_CONDITION",
        "START": "CONDITION_DATE"
    })
)

print("Latest Condition per patient (sample):")
latest_condition.head()

Latest Condition per patient (sample):

             HASHED_ID                   LATEST_CONDITION CONDITION_DATE
3341  967aac27324e0aab   Sprain (morphologic abnormality)     2026-05-26
1432  d7034ad1a0a6c127        Acute bronchitis (disorder)     2026-05-22
2132  5a121b78846cf3c5  Medication review due (situation)     2026-05-22
3168  7448e53142f5419f  Medication review due (situation)     2026-05-21
1269  b396e69852588f00   Primary dental caries (disorder)     2026-05-11

In [ ]:
master_view = patients_masked.copy()

master_view["HASHED_ID"] = master_view["Id"].apply(hash_value)
master_view = master_view.merge(total_cost, on="HASHED_ID", how="left")
master_view = master_view.merge(latest_condition, on="HASHED_ID", how="left")
master_view.drop(columns=["Id"], inplace=True)

master_view.head(5)

,BIRTHDATE,DEATHDATE,DRIVERS,PASSPORT,PREFIX,MIDDLE,SUFFIX,MAIDEN,MARITAL,RACE,...,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,INCOME,HASHED_ID,TOTAL_ENCOUNTER_COST,LATEST_CONDITION,CONDITION_DATE
0,1951-01-15,NaN,S99995838,X13314221X,Mrs.,Ashlie138,NaN,Runolfsson901,M,white,...,0,42.048896,-71.644746,781858.42,182267.18,53813,780f438829b05f6c,108261.21,Victim of intimate partner abuse (finding),2026-03-16
1,1957-10-27,NaN,S99916774,X60183820X,Mrs.,Janeth814,NaN,Cummerata161,D,white,...,1937,42.550276,-70.987312,617728.28,860065.14,109027,622014c1990471b2,119708.06,Viral sinusitis (disorder),2026-03-29
2,2005-12-04,NaN,S99960468,X16189809X,Ms.,Deandra603,NaN,NaN,NaN,white,...,1420,42.585057,-71.835094,11148.62,726893.50,125882,8cb3f03ca7ff8bf6,653126.57,Acute viral pharyngitis (disorder),2025-12-22
3,1978-05-14,NaN,S99981580,X20024386X,Mrs.,Valorie864,NaN,White193,M,asian,...,2144,42.399046,-71.132572,739328.17,135123.90,65255,f55ae149d39d40c6,141103.58,Stress (finding),2025-06-22
4,2013-09-09,NaN,NaN,NaN,NaN,Jenine75,NaN,NaN,NaN,black,...,1938,42.653922,-70.883568,17836.60,13403.05,136314,9f70fd9622d40e7d,24556.08,Gingivitis (disorder),2023-09-18

In [29]:
master_view.to_csv("output.csv", index=False)
master_view.head(5)

,BIRTHDATE,DEATHDATE,DRIVERS,PASSPORT,PREFIX,MIDDLE,SUFFIX,MAIDEN,MARITAL,RACE,...,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,INCOME,HASHED_ID,TOTAL_ENCOUNTER_COST,LATEST_CONDITION,CONDITION_DATE
0,1951-01-15,NaN,S99995838,X13314221X,Mrs.,Ashlie138,NaN,Runolfsson901,M,white,...,0,42.048896,-71.644746,781858.42,182267.18,53813,780f438829b05f6c,108261.21,Victim of intimate partner abuse (finding),2026-03-16
1,1957-10-27,NaN,S99916774,X60183820X,Mrs.,Janeth814,NaN,Cummerata161,D,white,...,1937,42.550276,-70.987312,617728.28,860065.14,109027,622014c1990471b2,119708.06,Viral sinusitis (disorder),2026-03-29
2,2005-12-04,NaN,S99960468,X16189809X,Ms.,Deandra603,NaN,NaN,NaN,white,...,1420,42.585057,-71.835094,11148.62,726893.50,125882,8cb3f03ca7ff8bf6,653126.57,Acute viral pharyngitis (disorder),2025-12-22
3,1978-05-14,NaN,S99981580,X20024386X,Mrs.,Valorie864,NaN,White193,M,asian,...,2144,42.399046,-71.132572,739328.17,135123.90,65255,f55ae149d39d40c6,141103.58,Stress (finding),2025-06-22
4,2013-09-09,NaN,NaN,NaN,NaN,Jenine75,NaN,NaN,NaN,black,...,1938,42.653922,-70.883568,17836.60,13403.05,136314,9f70fd9622d40e7d,24556.08,Gingivitis (disorder),2023-09-18